### ISSUE TITLE
slack bridge crashes with "Cannot read property 'image_72' of undefined" error

### ISSUE THREAD

**Issue by fadenb** [matrix-hacks/matrix-puppet-slack#14]
Hi,

I am running version 19e6575f0c2c249f45bb3428e1d913a2559b6fe6. I am not sure what triggered this. 

Last few lines of log output before process terminated:
```
Error: could not find slack team app for matrix room id
    at Promise (/nix/store/cmlib374fq2lnsrwgjkpsckg6g14f7p9-node-matrix-puppet-slack-1.4.0/lib/node_modules/matrix-puppet-slack/index.js:56:46)
    at Promise._execute (/nix/store/cmlib374fq2lnsrwgjkpsckg6g14f7p9-node-matrix-puppet-slack-1.4.0/lib/node_modules/matrix-puppet-slack/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/nix/store/cmlib374fq2lnsrwgjkpsckg6g14f7p9-node-matrix-puppet-slack-1.4.0/lib/node_modules/matrix-puppet-slack/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/nix/store/cmlib374fq2lnsrwgjkpsckg6g14f7p9-node-matrix-puppet-slack-1.4.0/lib/node_modules/matrix-puppet-slack/node_modules/bluebird/js/release/promise.js:79:10)
    at getAndCacheAppFromMatrixRoomId (/nix/store/cmlib374fq2lnsrwgjkpsckg6g14f7p9-node-matrix-puppet-slack-1.4.0/lib/node_modules/matrix-puppet-slack/index.js:41:14)
    at Object.onEvent (/nix/store/cmlib374fq2lnsrwgjkpsckg6g14f7p9-node-matrix-puppet-slack-1.4.0/lib/node_modules/matrix-puppet-slack/index.js:71:13)
    at Bridge._onConsume (/nix/store/cmlib374fq2lnsrwgjkpsckg6g14f7p9-node-matrix-puppet-slack-1.4.0/lib/node_modules/matrix-puppet-slack/node_modules/matrix-puppet-bridge/node_modules/matrix-appservice-bridge/lib/bridge.js:669:30)
    at /nix/store/cmlib374fq2lnsrwgjkpsckg6g14f7p9-node-matrix-puppet-slack-1.4.0/lib/node_modules/matrix-puppet-slack/node_modules/matrix-puppet-bridge/node_modules/matrix-appservice-bridge/lib/bridge.js:843:14
    at tryCatcher (/nix/store/cmlib374fq2lnsrwgjkpsckg6g14f7p9-node-matrix-puppet-slack-1.4.0/lib/node_modules/matrix-puppet-slack/node_modules/matrix-puppet-bridge/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/nix/store/cmlib374fq2lnsrwgjkpsckg6g14f7p9-node-matrix-puppet-slack-1.4.0/lib/node_modules/matrix-puppet-slack/node_modules/matrix-puppet-bridge/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/nix/store/cmlib374fq2lnsrwgjkpsckg6g14f7p9-node-matrix-puppet-slack-1.4.0/lib/node_modules/matrix-puppet-slack/node_modules/matrix-puppet-bridge/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/nix/store/cmlib374fq2lnsrwgjkpsckg6g14f7p9-node-matrix-puppet-slack-1.4.0/lib/node_modules/matrix-puppet-slack/node_modules/matrix-puppet-bridge/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/nix/store/cmlib374fq2lnsrwgjkpsckg6g14f7p9-node-matrix-puppet-slack-1.4.0/lib/node_modules/matrix-puppet-slack/node_modules/matrix-puppet-bridge/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/nix/store/cmlib374fq2lnsrwgjkpsckg6g14f7p9-node-matrix-puppet-slack-1.4.0/lib/node_modules/matrix-puppet-slack/node_modules/matrix-puppet-bridge/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/nix/store/cmlib374fq2lnsrwgjkpsckg6g14f7p9-node-matrix-puppet-slack-1.4.0/lib/node_modules/matrix-puppet-slack/node_modules/matrix-puppet-bridge/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
/nix/store/cmlib374fq2lnsrwgjkpsckg6g14f7p9-node-matrix-puppet-slack-1.4.0/lib/node_modules/matrix-puppet-slack/node_modules/matrix-puppet-bridge/node_modules/matrix-js-sdk/node_modules/olm/olm.js:19
"undefined"!==typeof module&&(module.exports=a);process.on("uncaughtException",function(a){if(!(a instanceof T))throw a;});a.inspect=function(){return"[Emscripten Module object]"}}else if(ma)a.print||(a.print=print),"undefined"!=typeof printErr&&(a.printErr=printErr),a.read="undefined"!=typeof read?read:function(){throw"no read() available (jsc?)";},a.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");z("object"===typeof a);return a},"undefined"!=
                                                    ^

TypeError: Cannot read property 'image_72' of undefined
    at Client.client.on.e (/nix/store/cmlib374fq2lnsrwgjkpsckg6g14f7p9-node-matrix-puppet-slack-1.4.0/lib/node_modules/matrix-puppet-slack/app.js:86:38)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at RTMClient.rtm.on (/nix/store/cmlib374fq2lnsrwgjkpsckg6g14f7p9-node-matrix-puppet-slack-1.4.0/lib/node_modules/matrix-puppet-slack/client.js:59:16)
    at RTMClient.emit (/nix/store/cmlib374fq2lnsrwgjkpsckg6g14f7p9-node-matrix-puppet-slack-1.4.0/lib/node_modules/matrix-puppet-slack/node_modules/@slack/client/node_modules/eventemitter3/index.js:116:35)
    at RTMClient.emit (/nix/store/cmlib374fq2lnsrwgjkpsckg6g14f7p9-node-matrix-puppet-slack-1.4.0/lib/node_modules/matrix-puppet-slack/node_modules/@slack/client/lib/clients/client.js:79:39)
    at RTMClient.handleWsMessage (/nix/store/cmlib374fq2lnsrwgjkpsckg6g14f7p9-node-matrix-puppet-slack-1.4.0/lib/node_modules/matrix-puppet-slack/node_modules/@slack/client/lib/clients/rtm/client.js:406:8)
    at WebSocket.wrapper (/nix/store/cmlib374fq2lnsrwgjkpsckg6g14f7p9-node-matrix-puppet-slack-1.4.0/lib/node_modules/matrix-puppet-slack/node_modules/@slack/client/node_modules/lodash/lodash.js:4968:19)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/nix/store/cmlib374fq2lnsrwgjkpsckg6g14f7p9-node-matrix-puppet-slack-1.4.0/lib/node_modules/matrix-puppet-slack/node_modules/@slack/client/node_modules/ws/lib/WebSocket.js:841:10)
    at /nix/store/cmlib374fq2lnsrwgjkpsckg6g14f7p9-node-matrix-puppet-slack-1.4.0/lib/node_modules/matrix-puppet-slack/node_modules/@slack/client/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/nix/store/cmlib374fq2lnsrwgjkpsckg6g14f7p9-node-matrix-puppet-slack-1.4.0/lib/node_modules/matrix-puppet-slack/node_modules/@slack/client/node_modules/ws/lib/Receiver.js:371:5)
    at /nix/store/cmlib374fq2lnsrwgjkpsckg6g14f7p9-node-matrix-puppet-slack-1.4.0/lib/node_modules/matrix-puppet-slack/node_modules/@slack/client/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (/nix/store/cmlib374fq2lnsrwgjkpsckg6g14f7p9-node-matrix-puppet-slack-1.4.0/lib/node_modules/matrix-puppet-slack/node_modules/@slack/client/node_modules/ws/lib/Receiver.js:347:3)
    at Receiver.finish (/nix/store/cmlib374fq2lnsrwgjkpsckg6g14f7p9-node-matrix-puppet-slack-1.4.0/lib/node_modules/matrix-puppet-slack/node_modules/@slack/client/node_modules/ws/lib/Receiver.js:541:12)
    at Receiver.expectHandler (/nix/store/cmlib374fq2lnsrwgjkpsckg6g14f7p9-node-matrix-puppet-slack-1.4.0/lib/node_modules/matrix-puppet-slack/node_modules/@slack/client/node_modules/ws/lib/Receiver.js:499:31)
    at Receiver.add (/nix/store/cmlib374fq2lnsrwgjkpsckg6g14f7p9-node-matrix-puppet-slack-1.4.0/lib/node_modules/matrix-puppet-slack/node_modules/@slack/client/node_modules/ws/lib/Receiver.js:103:24)
    at TLSSocket.realHandler (/nix/store/cmlib374fq2lnsrwgjkpsckg6g14f7p9-node-matrix-puppet-slack-1.4.0/lib/node_modules/matrix-puppet-slack/node_modules/@slack/client/node_modules/ws/lib/WebSocket.js:825:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)

[fadenb@m00:~/matrix-puppet-slack]$
```

**Comment by fadenb** [comment]
I was able to reproduce the issue. I was writing (in slack native webinterface) to a coworker that was in DND mode. The reponse from the slackbot crashed the bridge with the same message as posted earlier.

![crash_example](https://cloud.githubusercontent.com/assets/878822/23668996/1678ba12-0363-11e7-8dd6-e0dc6d82a5f3.png)
The time of day shown in the screenshot correlates with the error in the logfile.

**Comment by kfatehi** [comment]
slackbot is supported properly now
