### ISSUE TITLE
Bridge silently ignores "/me bla bla" messages

### ISSUE THREAD

**Issue by fadenb** [matrix-hacks/matrix-puppet-slack#17]
Hey :)

Just noticed that messages I write in Matrix room (direct message) of the type `/me says something` are silently ignored and not visible in slack.

A warning might be nice until this is implemented :)

**Comment by Sorunome** [comment]
The new, still in development [matrix-puppet-server](https://github.com/matrix-hacks/matrix-puppet-server) api thing adds in /me support, check the https://github.com/matrix-hacks/matrix-puppet-slack/tree/develop_new branch for the slack implementation. Use at your own risk!

**Comment by thomas-profitt** [comment]
Confirming that this is still an issue.

/me messages sent from Matrix are silently ignored.

/me messages sent from Slack are passed through as if they were regular messages and aren't formatted or turned into Matrix emotes.

**Comment by thomas-profitt** [comment]
The bridge does throw this error and notify when I try to /me from Matrix:
```
Error in handleMatrixEvent { Error: dont know how to handle this msgtype
    at promise (/app/node_modules/matrix-puppet-bridge/src/base.js:811:40)
    at App.handleMatrixMessageEvent (/app/node_modules/matrix-puppet-bridge/src/base.js:815:12)
    at App.handleMatrixEvent (/app/node_modules/matrix-puppet-bridge/src/base.js:760:19)
    at getAndCacheAppFromMatrixRoomId.then.app (/app/index.js:73:26)
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/app/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
  [stack]: 'Error: dont know how to handle this msgtype\n    at promise (/app/node_modules/matrix-puppet-bridge/src/base.js:811:40)\n    at App.handleMatrixMessageEvent (/app/node_modules/matrix-puppet-bridge/src/base.js:815:12)\n    at App.handleMatrixEvent (/app/node_modules/matrix-puppet-bridge/src/base.js:760:19)\n    at getAndCacheAppFromMatrixRoomId.then.app (/app/index.js:73:26)\n    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromiseCtx (/app/node_modules/bluebird/js/release/promise.js:606:10)\n    at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:138:12)\n    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:756:18)\n    at tryOnImmediate (timers.js:717:5)\n    at processImmediate [as _immediateCallback] (timers.js:697:5)',
  [message]: 'dont know how to handle this msgtype' } { age: 164,
  content: { body: 'does something', msgtype: 'm.emote' },
  event_id: 'REDACTED',
  origin_server_ts: 1540755450157,
  room_id: 'REDACTED',
  sender: 'REDACTED',
  type: 'm.room.message',
  unsigned: { age: 164 },
  user_id: 'REDACTED' } ﻿
```
