### ISSUE TITLE
direct messages throwing error in slack room

### ISSUE THREAD

**Issue by kfatehi** [matrix-hacks/matrix-puppet-slack#18]
https://github.com/matrix-hacks/matrix-puppet-slack/commit/c56a1d0f4ecfb051c4b05d2bf15efaea4d56bba9#commitcomment-21307379

**Comment by kfatehi** [comment]
this is not actually happening on my HS, but need to investigate

**Comment by kfatehi** [comment]
It's happening now on my HS (Yippee!!):

```
TypeError: Cannot read property 'isDirect' of null
    at App.getThirdPartyRoomDataById (/home/keyvan/bridges/slack/app.js:133:17)
    at puppetClient.getRoomIdForAlias.then (/home/keyvan/bridges/mpb/src/base.js:293:35)
    at _rejected (/home/keyvan/bridges/mpb/node_modules/q/q.js:844:24)
    at /home/keyvan/bridges/mpb/node_modules/q/q.js:870:30
    at Promise.when (/home/keyvan/bridges/mpb/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/home/keyvan/bridges/mpb/node_modules/q/q.js:788:41)
    at /home/keyvan/bridges/mpb/node_modules/q/q.js:604:44
    at runSingle (/home/keyvan/bridges/mpb/node_modules/q/q.js:137:13)
    at flush (/home/keyvan/bridges/mpb/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
TypeError: Cannot read property 'isDirect' of null
    at App.getThirdPartyRoomDataById (/home/keyvan/bridges/slack/app.js:133:17)
    at puppetClient.getRoomIdForAlias.then (/home/keyvan/bridges/mpb/src/base.js:293:35)
    at _rejected (/home/keyvan/bridges/mpb/node_modules/q/q.js:844:24)
    at /home/keyvan/bridges/mpb/node_modules/q/q.js:870:30
    at Promise.when (/home/keyvan/bridges/mpb/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/home/keyvan/bridges/mpb/node_modules/q/q.js:788:41)
    at /home/keyvan/bridges/mpb/node_modules/q/q.js:604:44
    at runSingle (/home/keyvan/bridges/mpb/node_modules/q/q.js:137:13)
    at flush (/home/keyvan/bridges/mpb/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
TypeError: Cannot read property 'isDirect' of null
    at App.getThirdPartyRoomDataById (/home/keyvan/bridges/slack/app.js:133:17)
    at puppetClient.getRoomIdForAlias.then (/home/keyvan/bridges/mpb/src/base.js:293:35)
    at _rejected (/home/keyvan/bridges/mpb/node_modules/q/q.js:844:24)
    at /home/keyvan/bridges/mpb/node_modules/q/q.js:870:30
    at Promise.when (/home/keyvan/bridges/mpb/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/home/keyvan/bridges/mpb/node_modules/q/q.js:788:41)
    at /home/keyvan/bridges/mpb/node_modules/q/q.js:604:44
    at runSingle (/home/keyvan/bridges/mpb/node_modules/q/q.js:137:13)
    at flush (/home/keyvan/bridges/mpb/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
TypeError: Cannot read property 'isDirect' of null
    at App.getThirdPartyRoomDataById (/home/keyvan/bridges/slack/app.js:133:17)
    at puppetClient.getRoomIdForAlias.then (/home/keyvan/bridges/mpb/src/base.js:293:35)
    at _rejected (/home/keyvan/bridges/mpb/node_modules/q/q.js:844:24)
    at /home/keyvan/bridges/mpb/node_modules/q/q.js:870:30
    at Promise.when (/home/keyvan/bridges/mpb/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/home/keyvan/bridges/mpb/node_modules/q/q.js:788:41)
    at /home/keyvan/bridges/mpb/node_modules/q/q.js:604:44
    at runSingle (/home/keyvan/bridges/mpb/node_modules/q/q.js:137:13)
    at flush (/home/keyvan/bridges/mpb/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
TypeError: Cannot read property 'isDirect' of null
    at App.getThirdPartyRoomDataById (/home/keyvan/bridges/slack/app.js:133:17)
    at puppetClient.getRoomIdForAlias.then (/home/keyvan/bridges/mpb/src/base.js:293:35)
    at _rejected (/home/keyvan/bridges/mpb/node_modules/q/q.js:844:24)
    at /home/keyvan/bridges/mpb/node_modules/q/q.js:870:30
    at Promise.when (/home/keyvan/bridges/mpb/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/home/keyvan/bridges/mpb/node_modules/q/q.js:788:41)
    at /home/keyvan/bridges/mpb/node_modules/q/q.js:604:44
    at runSingle (/home/keyvan/bridges/mpb/node_modules/q/q.js:137:13)
    at flush (/home/keyvan/bridges/mpb/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
S
13:40
TypeError: Cannot read property 'isDirect' of null
    at App.getThirdPartyRoomDataById (/home/keyvan/bridges/slack/app.js:133:17)
    at puppetClient.getRoomIdForAlias.then (/home/keyvan/bridges/mpb/src/base.js:293:35)
    at _rejected (/home/keyvan/bridges/mpb/node_modules/q/q.js:844:24)
    at /home/keyvan/bridges/mpb/node_modules/q/q.js:870:30
    at Promise.when (/home/keyvan/bridges/mpb/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/home/keyvan/bridges/mpb/node_modules/q/q.js:788:41)
    at /home/keyvan/bridges/mpb/node_modules/q/q.js:604:44
    at runSingle (/home/keyvan/bridges/mpb/node_modules/q/q.js:137:13)
    at flush (/home/keyvan/bridges/mpb/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

**Comment by Sorunome** [comment]
Perhaps this is related to #11 or #20 ?

**Comment by thomas-profitt** [comment]
I can confirm this problem on https://github.com/matrix-hacks/matrix-puppet-slack/commit/4affd67f0b7d410c8b5209d9a8eab7116b7756dd

It happened most recently when a multi-channel guest DM'd me, 3 messages, for the first time. This error was thrown each time. When I responded in the DM, in Slack, the Matrix room was created, with my message. The other user's subsequent messages in that DM _did_ all show up, without a hitch.
