### ISSUE TITLE
Could not find slack team app for matrix room id

### ISSUE THREAD

**Issue by Sorunome** [matrix-hacks/matrix-puppet-slack#21]
The puppeting link is working just fine, however i am getting these errors all over:
```
Error: could not find slack team app for matrix room id
    at Promise (/home/sorunome/matrix-puppet-slack/index.js:56:46)
    at Promise._execute (/home/sorunome/matrix-puppet-slack/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/home/sorunome/matrix-puppet-slack/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/sorunome/matrix-puppet-slack/node_modules/bluebird/js/release/promise.js:79:10)
    at getAndCacheAppFromMatrixRoomId (/home/sorunome/matrix-puppet-slack/index.js:41:14)
    at Object.onEvent (/home/sorunome/matrix-puppet-slack/index.js:71:13)
    at Bridge._onConsume (/home/sorunome/matrix-puppet-slack/node_modules/matrix-appservice-bridge/lib/bridge.js:715:30)
    at /home/sorunome/matrix-puppet-slack/node_modules/matrix-appservice-bridge/lib/bridge.js:917:14
    at tryCatcher (/home/sorunome/matrix-puppet-slack/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/sorunome/matrix-puppet-slack/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/sorunome/matrix-puppet-slack/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/sorunome/matrix-puppet-slack/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/sorunome/matrix-puppet-slack/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/sorunome/matrix-puppet-slack/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/sorunome/matrix-puppet-slack/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
```

**Comment by Sorunome** [comment]
OK, i figured out this one. This is actually an issue of the bridge:

If you are in a channel where other users are which start with `@slack_` but isn't part of your puppeted slack, such as `#matrix:matrix.org` the regex in `slack-registration.yaml` will give a alse positive.

To fix this, change the regex from like `regex: '@slack_.*'` to `regex: '@slack_.*:sorunome.de'` where `sorunome.de` is your homeserver thing
