### ISSUE TITLE
Messages from some slack users don't show up in Matrix

### ISSUE THREAD

**Issue by gerco** [matrix-hacks/matrix-puppet-slack#23]
I'm using matrix-puppet-slack and a private HS. I have it bridged to a single Slack team. When one particular user writes any messages in Slack, the messages don't show up on Matrix and I see the following message in the Slack Protocol room:

```
Error in handleThirdPartyRoomMessage { Error: Argument error, options.body.
    at setContentLength (/root/matrix-puppet-slack/node_modules/request/request.js:439:28)
    at Request.init (/root/matrix-puppet-slack/node_modules/request/request.js:444:5)
    at new Request (/root/matrix-puppet-slack/node_modules/request/request.js:130:8)
    at request (/root/matrix-puppet-slack/node_modules/request/index.js:54:10)
    at /root/matrix-puppet-slack/node_modules/matrix-appservice-bridge/lib/components/client-factory.js:54:9
    at Object.request (/root/matrix-puppet-slack/node_modules/matrix-appservice-bridge/node_modules/matrix-js-sdk/lib/matrix.js:102:16)
    at Object._request (/root/matrix-puppet-slack/node_modules/matrix-appservice-bridge/node_modules/matrix-js-sdk/lib/http-api.js:649:29)
    at Object.requestOtherUrl (/root/matrix-puppet-slack/node_modules/matrix-appservice-bridge/node_modules/matrix-js-sdk/lib/http-api.js:558:21)
    at Object.request (/root/matrix-puppet-slack/node_modules/matrix-appservice-bridge/node_modules/matrix-js-sdk/lib/http-api.js:443:21)
    at Object.authedRequest (/root/matrix-puppet-slack/node_modules/matrix-appservice-bridge/node_modules/matrix-js-sdk/lib/http-api.js:392:36)
    at Object.uploadContent (/root/matrix-puppet-slack/node_modules/matrix-appservice-bridge/node_modules/matrix-js-sdk/lib/http-api.js:276:28)
    at MatrixClient.MatrixBaseApis.uploadContent (/root/matrix-puppet-slack/node_modules/matrix-appservice-bridge/node_modules/matrix-js-sdk/lib/base-apis.js:639:23)
    at download.getBufferAndType.then (/root/matrix-puppet-slack/node_modules/matrix-puppet-bridge/src/base.js:860:25)
    at tryCatcher (/root/matrix-puppet-slack/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/matrix-puppet-slack/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/root/matrix-puppet-slack/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/root/matrix-puppet-slack/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/root/matrix-puppet-slack/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/root/matrix-puppet-slack/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/root/matrix-puppet-slack/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/root/matrix-puppet-slack/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
  [stack]: [Getter/Setter],
  [message]: 'Argument error, options.body.' } { 
  roomId: '---removed---',
  senderId: '---removed---',
  senderName: '---removed---',
  avatarUrl: 'https://secure.gravatar.com/avatar/---removed---',
  text: '(like gerco blogging)',
  html: '
(like gerco blogging)

' } ﻿
```

I removed a few personally identifying details (---removed---) but otherwise the above message is verbatim. Any ideas for debugging this? 

I've tried to look at the bridge code and will look some more if this is not a known issue but I didn't see anything. My unfamiliarity with js, matrix and slack may have something to do with my inability to find the issue.

**Comment by Sorunome** [comment]
Do said users happen to not have an avatar set on the slack side?

**Comment by gerco** [comment]
I checked and that does appear to be the case for at least two of them. I did not find any counter examples so it looks like your suggestion may be correct.

**Comment by thomas-profitt** [comment]
@gerco, I had this problem too.

Slack's default avatars' URLs have a redirect or two before the actual image is served, and matrix-puppet-bridge was not following redirects when requesting the images, and it wigged out.

This change in matrix-puppet-bridge fixed it:
https://github.com/matrix-hacks/matrix-puppet-bridge/commit/39144bcaa2d6e448507631e8b5269e4ee30b6343

Update "matrix-puppet-bridge" to "1.15.3" in your _package.json_, run `npm install`, and restart matrix-puppet-slack.

**Comment by thomas-profitt** [comment]
Going to call this closed with https://github.com/matrix-hacks/matrix-puppet-slack/pull/26
