### ISSUE TITLE
Images uploaded on Slack show as "undefined"

### ISSUE THREAD

**Issue by zielmicha** [matrix-hacks/matrix-puppet-slack#30]
Images uploaded on Slack show up on Matrix as:
`[Image] (undefined) undefined `

Node.js version: v8.10.0
Matrix puppet bridge version: v1.15.2

Replacing `const isFilenameTagged = (filepath) => !!filepath.match(FILENAME_TAG_PATTERN);` with `const isFilenameTagged = (filepath) => (filepath && !!filepath.match(FILENAME_TAG_PATTERN));` in utils.js fixes the issue.

The log:

```
Mar 08 06:02:11 matrix node[11672]: { type: 'message',
Mar 08 06:02:11 matrix node[11672]:   subtype: 'file_share',
Mar 08 06:02:11 matrix node[11672]:   text: '<@XXXXX> uploaded a file: <https://XXXXX.slack.com/files/XXXXX/XXXXX/image__2_.png|image (2).png>',
Mar 08 06:02:11 matrix node[11672]:   file:
Mar 08 06:02:11 matrix node[11672]:    { id: 'XXXXX',
Mar 08 06:02:11 matrix node[11672]:      created: 1520488929,
Mar 08 06:02:11 matrix node[11672]:      timestamp: 1520488929,
Mar 08 06:02:11 matrix node[11672]:      name: 'image (2).png',
Mar 08 06:02:11 matrix node[11672]:      title: 'image (2).png',
Mar 08 06:02:11 matrix node[11672]:      mimetype: 'image/png',
Mar 08 06:02:11 matrix node[11672]:      filetype: 'png',
Mar 08 06:02:11 matrix node[11672]:      pretty_type: 'PNG',
Mar 08 06:02:11 matrix node[11672]:      user: 'XXXXX',
Mar 08 06:02:11 matrix node[11672]:      editable: false,
Mar 08 06:02:11 matrix node[11672]:      size: 34804,
Mar 08 06:02:11 matrix node[11672]:      mode: 'hosted',
Mar 08 06:02:11 matrix node[11672]:      is_external: false,
Mar 08 06:02:11 matrix node[11672]:      external_type: '',
Mar 08 06:02:11 matrix node[11672]:      is_public: false,
Mar 08 06:02:11 matrix node[11672]:      public_url_shared: false,
Mar 08 06:02:11 matrix node[11672]:      display_as_bot: false,
Mar 08 06:02:11 matrix node[11672]:      username: '',
Mar 08 06:02:11 matrix node[11672]:      url_private: 'https://files.slack.com/files-pri/XXXXX-XXXXX/image__2_.png',
Mar 08 06:02:11 matrix node[11672]:      url_private_download: 'https://files.slack.com/files-pri/XXXXX-XXXXX/download/image__2_.png',
Mar 08 06:02:11 matrix node[11672]:      thumb_64: 'https://files.slack.com/files-tmb/XXXXX-XXXXX-XXXXX/image__2__64.png',
Mar 08 06:02:11 matrix node[11672]:      thumb_80: 'https://files.slack.com/files-tmb/XXXXX-XXXXX-XXXXX/image__2__80.png',
Mar 08 06:02:11 matrix node[11672]:      thumb_360: 'https://files.slack.com/files-tmb/XXXXX-XXXXX-XXXXX/image__2__360.png',
Mar 08 06:02:11 matrix node[11672]:      thumb_360_w: 360,
Mar 08 06:02:11 matrix node[11672]:      thumb_360_h: 297,
Mar 08 06:02:11 matrix node[11672]:      thumb_480: 'https://files.slack.com/files-tmb/XXXXX-XXXXX-XXXXX/image__2__480.png',
Mar 08 06:02:11 matrix node[11672]:      thumb_480_w: 480,
Mar 08 06:02:11 matrix node[11672]:      thumb_480_h: 396,
Mar 08 06:02:11 matrix node[11672]:      thumb_160: 'https://files.slack.com/files-tmb/XXXXX-XXXXX-XXXXX/image__2__160.png',
Mar 08 06:02:11 matrix node[11672]:      image_exif_rotation: 1,
Mar 08 06:02:11 matrix node[11672]:      original_w: 706,
Mar 08 06:02:11 matrix node[11672]:      original_h: 582,
Mar 08 06:02:11 matrix node[11672]:      permalink: 'https://XXXXX.slack.com/files/XXXXX/XXXXX/image__2_.png',
Mar 08 06:02:11 matrix node[11672]:      permalink_public: 'https://slack-files.com/XXXXX-XXXXX-XXXXX',
Mar 08 06:02:11 matrix node[11672]:      channels: [],
Mar 08 06:02:11 matrix node[11672]:      groups: [],
Mar 08 06:02:11 matrix node[11672]:      ims: [ 'XXXXX' ],
Mar 08 06:02:11 matrix node[11672]:      comments_count: 0 },
Mar 08 06:02:11 matrix node[11672]:   user: 'XXXXX',
Mar 08 06:02:11 matrix node[11672]:   upload: true,
Mar 08 06:02:11 matrix node[11672]:   display_as_bot: false,
Mar 08 06:02:11 matrix node[11672]:   username: 'zielmicha',
Mar 08 06:02:11 matrix node[11672]:   bot_id: null,
Mar 08 06:02:11 matrix node[11672]:   team: 'XXXXX',
Mar 08 06:02:11 matrix node[11672]:   source_team: 'XXXXX',
Mar 08 06:02:11 matrix node[11672]:   user_team: 'XXXXX',
Mar 08 06:02:11 matrix node[11672]:   user_profile:
Mar 08 06:02:11 matrix node[11672]:    { avatar_hash: 'g4ad644788c5',
Mar 08 06:02:11 matrix node[11672]:      image_72: 'https://secure.gravatar.com/avatar/4ad644788c54cbb5c7ed7e6b611e5577.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2F66f9%2Fimg%2Favatars%2Fava_0000-72.png',
Mar 08 06:02:11 matrix node[11672]:      first_name: 'Michał',
Mar 08 06:02:11 matrix node[11672]:      real_name: 'XXXX',
Mar 08 06:02:11 matrix node[11672]:      display_name: 'zielmicha',
Mar 08 06:02:11 matrix node[11672]:      team: 'XXXXX',
Mar 08 06:02:11 matrix node[11672]:      name: 'zielmicha',
Mar 08 06:02:11 matrix node[11672]:      is_restricted: false,
Mar 08 06:02:11 matrix node[11672]:      is_ultra_restricted: false },
Mar 08 06:02:11 matrix node[11672]:   channel: 'XXXX',
Mar 08 06:02:11 matrix node[11672]:   event_ts: 'XXX',
Mar 08 06:02:11 matrix node[11672]:   ts: 'XXX' }
Mar 08 06:02:11 matrix node[11672]: [-] PUT https://matrix.zielmicha.com:8448/_matrix/client/r0/rooms/!XXXXXX%3Azielmicha.com/state/m.room.power_levels (AS) Body: {"users_default":0,"events_default":0,"state_default":50,"users":{"@slack_bot:zi
Mar 08 06:02:11 matrix node[11672]: [-] PUT https://matrix.zielmicha.com:8448/_matrix/client/r0/rooms/!DgOLRzVkQBXWlpPeuZ%3Azielmicha.com/state/m.room.power_levels (AS) HTTP 200 {"event_id":"$152048893124UyVnF:zielmicha.com"}
Mar 08 06:02:12 matrix node[11672]: TypeError: Cannot read property 'match' of undefined
Mar 08 06:02:12 matrix node[11672]:     at isFilenameTagged (/matrix/apps/zielmicha-slack/node_modules/matrix-puppet-bridge/src/utils.js:57:51)
Mar 08 06:02:12 matrix node[11672]:     at getUserClient.then (/matrix/apps/zielmicha-slack/node_modules/matrix-puppet-bridge/src/base.js:644:56)
Mar 08 06:02:12 matrix node[11672]:     at tryCatcher (/matrix/apps/zielmicha-slack/node_modules/bluebird/js/release/util.js:16:23)
Mar 08 06:02:12 matrix node[11672]:     at Promise._settlePromiseFromHandler (/matrix/apps/zielmicha-slack/node_modules/bluebird/js/release/promise.js:512:31)
Mar 08 06:02:12 matrix node[11672]:     at Promise._settlePromise (/matrix/apps/zielmicha-slack/node_modules/bluebird/js/release/promise.js:569:18)
Mar 08 06:02:12 matrix node[11672]:     at Promise._settlePromiseCtx (/matrix/apps/zielmicha-slack/node_modules/bluebird/js/release/promise.js:606:10)
Mar 08 06:02:12 matrix node[11672]:     at Async._drainQueue (/matrix/apps/zielmicha-slack/node_modules/bluebird/js/release/async.js:138:12)
Mar 08 06:02:12 matrix node[11672]:     at Async._drainQueues (/matrix/apps/zielmicha-slack/node_modules/bluebird/js/release/async.js:143:10)
Mar 08 06:02:12 matrix node[11672]:     at Immediate.Async.drainQueues (/matrix/apps/zielmicha-slack/node_modules/bluebird/js/release/async.js:17:14)
Mar 08 06:02:12 matrix node[11672]:     at runCallback (timers.js:794:20)
Mar 08 06:02:12 matrix node[11672]:     at tryOnImmediate (timers.js:752:5)
Mar 08 06:02:12 matrix node[11672]:     at processImmediate [as _immediateCallback] (timers.js:729:5)
```

**Comment by thomas-profitt** [comment]
Since this issue was created, Slack changed and broke images for us entirely, then out 1.7.0 fixed images, and now everything's working for me. Closing this since it's surely no longer relevant.
