### ISSUE TITLE
Installation script fails

### ISSUE THREAD

**Issue by serussell** [matrix-hacks/matrix-puppet-slack#44]
Following the install instructions in the readme fails.  It looks like the installation script is using the wrong method to call a web service during set-up:

```
util% npm install      
npm WARN package.json matrix-puppet-slack@1.6.0 No repository field.
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-042stab120.6
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/XXX/opt/matrix-puppet-slack
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/XXX/opt/matrix-puppet-slack/npm-debug.log
npm ERR! not ok code 0
```

In the big node log, I see:

```
248 http 405 https://registry.npmjs.org/slack/client 
```

Indeed, calling this with a browser returns the same error:

```
{"code":"MethodNotAllowedError","message":"GET is not allowed"}
```

**Comment by kfatehi** [comment]
Hi @serussell 
I believe it is trying to download https://www.npmjs.com/package/@slack/client and it can't. Your npm version might be too old.

**Comment by serussell** [comment]
@kfatehi Eeeeyup.  That was it.  Debian on that VM had node 1.4, or something like that.

Thanks.
