### ISSUE TITLE
Matrix -> Slack not working

### ISSUE THREAD

**Issue by zazard** [matrix-hacks/matrix-puppet-slack#8]
Hi, first thanks for making this !

I'm able to connect to one slack team, and receive messages from slack.
However sending from matrix to slack does not seem to work. These are the errors in my log:

```::ffff:127.0.0.1 - - [04/Mar/2017:14:04:27 +0000] "PUT /transactions/37?access_token=<REDACTED> HTTP/1.1" 200 2 "-" "Synapse/0.19.2"



TypeError: Cannot read property 'name' of null
    at App.getThirdPartyRoomDataById (/home/zaz/matrix-puppet-slack/app.js:95:17)
    at puppetClient.getRoomIdForAlias.then (/home/zaz/matrix-puppet-slack/node_modules/matrix-puppet-bridge/src/base.js:291:35)
    at _rejected (/home/zaz/matrix-puppet-slack/node_modules/q/q.js:844:24)
    at /home/zaz/matrix-puppet-slack/node_modules/q/q.js:870:30
    at Promise.when (/home/zaz/matrix-puppet-slack/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/home/zaz/matrix-puppet-slack/node_modules/q/q.js:788:41)
    at /home/zaz/matrix-puppet-slack/node_modules/q/q.js:604:44
    at runSingle (/home/zaz/matrix-puppet-slack/node_modules/q/q.js:137:13)
    at flush (/home/zaz/matrix-puppet-slack/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
EventTimelineSet.addLiveEvent: ignoring duplicate event $148863634936IDdeZ:poneybl.eu
::ffff:127.0.0.1 - - [04/Mar/2017:14:07:15 +0000] "PUT /transactions/38?access_token=<REDACTED> HTTP/1.1" 200 2 "-" "Synapse/0.19.2"

Error: could not find slack team app for matrix room id
    at Promise (/home/zaz/matrix-puppet-slack/index.js:56:46)
    at Promise._execute (/home/zaz/matrix-puppet-slack/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/home/zaz/matrix-puppet-slack/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/zaz/matrix-puppet-slack/node_modules/bluebird/js/release/promise.js:79:10)
    at getAndCacheAppFromMatrixRoomId (/home/zaz/matrix-puppet-slack/index.js:41:14)
    at Object.onEvent (/home/zaz/matrix-puppet-slack/index.js:71:13)
    at Bridge._onConsume (/home/zaz/matrix-puppet-slack/node_modules/matrix-appservice-bridge/lib/bridge.js:669:30)
    at /home/zaz/matrix-puppet-slack/node_modules/matrix-appservice-bridge/lib/bridge.js:843:14
    at tryCatcher (/home/zaz/matrix-puppet-slack/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/zaz/matrix-puppet-slack/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/zaz/matrix-puppet-slack/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/zaz/matrix-puppet-slack/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/zaz/matrix-puppet-slack/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/zaz/matrix-puppet-slack/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/zaz/matrix-puppet-slack/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)

```

**Comment by kfatehi** [comment]
the error "could not find slack team app for matrix room id" is supposed to have a room id at the end. so it looks like it was called with an empty string '' or something, which should never happen... also this error should have been produced first because this is the routine which determines which team the matrix room you sent from is meant to represent.

"Cannot read property 'name' of null" happens after a team has been determined (app.js is 1:1 with a team) and we try to getRoomById (third party, slack room ID) ......

it's pretty confusing and unclear without good context and perhaps even some more debug logging is necessary. 

you can try running with `DEBUG=matrix-puppet:* node index.js` (`npm start` does this) and see if the problem reveals itself.

**Comment by kfatehi** [comment]
closing because it's been a week
