### ISSUE TITLE
Messages are notified in console, but no data in client

### ISSUE THREAD

**Issue by kalon33** [matrix-hacks/matrix-puppet-slack#82]
I just installed matrix-puppet-slack, and while I properly see messages in console, I got nothing in my client. Here is the log of the error (after each message):

```
{ [M_EXCLUSIVE: This application service has not reserved this kind of alias.]
  errcode: 'M_EXCLUSIVE',
  name: 'M_EXCLUSIVE',
  message: 'This application service has not reserved this kind of alias.',
  data: 
   { errcode: 'M_EXCLUSIVE',
     error: 'This application service has not reserved this kind of alias.' },
  httpStatus: 400 }
Unhandled rejection TypeError: Cannot read property 'toString' of undefined
    at args.reduce (/home/nicolas/matrix-puppet-slack/node_modules/matrix-puppet-bridge/src/base.js:389:28)
    at Array.reduce (<anonymous>)
    at App.sendStatusMsg (/home/nicolas/matrix-puppet-slack/node_modules/matrix-puppet-bridge/src/base.js:384:26)
    at getIntentFromThirdPartySenderId.then.catch.err (/home/nicolas/matrix-puppet-slack/app.js:369:12)
    at tryCatcher (/home/nicolas/matrix-puppet-slack/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/nicolas/matrix-puppet-slack/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/nicolas/matrix-puppet-slack/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/nicolas/matrix-puppet-slack/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/nicolas/matrix-puppet-slack/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/home/nicolas/matrix-puppet-slack/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/nicolas/matrix-puppet-slack/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/nicolas/matrix-puppet-slack/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/home/nicolas/matrix-puppet-slack/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

**Comment by MrFunken** [comment]
Got the same issue on my installation
