### ISSUE TITLE
Puppet cannot be started

### ISSUE THREAD

**Issue by hooger** [matrix-hacks/matrix-puppet-slack#84]
Hello,
I'm trying to start the service but it says:

```
>> node index.js
Unable to load crypto module: crypto will be disabled: Error: global.Olm is not defined
Unable to load crypto module: crypto will be disabled: Error: global.Olm is not defined
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8090
    at Server.setupListenHandle [as _listen2] (net.js:1346:14)
    at listenInCluster (net.js:1387:12)
    at Server.listen (net.js:1475:7)
    at Function.listen (/usr/local/src/matrix-puppet-slack/node_modules/express/lib/application.js:618:24)
    at AppService.listen (/usr/local/src/matrix-puppet-slack/node_modules/matrix-appservice/lib/app-service.js:209:18)
    at Bridge.run (/usr/local/src/matrix-puppet-slack/node_modules/matrix-appservice-bridge/lib/bridge.js:304:21)
    at Object.run (/usr/local/src/matrix-puppet-slack/index.js:99:19)
    at Cli._startWithConfig (/usr/local/src/matrix-puppet-slack/node_modules/matrix-appservice-bridge/lib/components/cli.js:181:15)
    at Cli.run (/usr/local/src/matrix-puppet-slack/node_modules/matrix-appservice-bridge/lib/components/cli.js:140:10)
    at Object.<anonymous> (/usr/local/src/matrix-puppet-slack/index.js:126:4)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1366:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```

Any idea where I should start debugging? System is Debian 9, up-to-date. matrix-puppet-facebook works.
Thank you for the help in advance!

**Comment by hooger** [comment]
The problem was, that Facebook puppet was running on 8090 port already. Clue is the 
`listen EADDRINUSE :::8090` line.
Thank for the help on the channel!
